---
name: "Setup Podman Environment"
description: "Prepare Podman for rootless builds"

runs:
  using: "composite"
  steps:

    - name: Remove Docker if installed
      shell: bash
      run: |
        if command -v docker >/dev/null 2>&1; then
          echo "Docker found removing"
          sudo systemctl stop docker docker.socket || true
          sudo apt-get purge -y \
            docker \
            docker.io \
            docker-ce \
            docker-ce-cli \
            containerd runc || true
          sudo apt-get autoremove -y
          sudo rm -rf /var/lib/docker /var/lib/containerd
        else
          echo "Docker not installed"
        fi

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          podman \
          python3-pip \
          fuse-overlayfs \
          uidmap \
          qemu-user-static \
          yq

    - name: Enable lingering for current user
      shell: bash
      run: |
        sudo loginctl enable-linger $USER || true

    - name: Create Podman config directories
      shell: bash
      run: |
        mkdir -p ~/.config/containers
        mkdir -p ~/.local/share/containers

    - name: Configure rootless Podman storage
      shell: bash
      run: |
        cat <<'EOF' > ~/.config/containers/storage.conf
          [storage]
          driver = "overlay"
          runroot = "/tmp/run-$(id -u)"
          graphroot = "$HOME/.local/share/containers/storage"
          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
        EOF

    - name: Migrate Podman storage (if needed)
      shell: bash
      run: |
        podman system migrate || true

    - name: Install podman-compose from PyPI
      shell: bash
      run: |
        pip install --upgrade pip
        pip install podman-compose

    - name: Verify Podman and podman-compose
      shell: bash
      run: |
        podman --version
        podman-compose version
